{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "inferplane.fullname" . }}
  labels:
    {{- include "inferplane.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- with .Values.ingress.data.host }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.ingress.data.path }}
            pathType: {{ $.Values.ingress.data.pathType }}
            backend:
              service:
                name: {{ include "inferplane.fullname" $ }}
                port:
                  name: data
    {{- end }}
    {{- if .Values.ingress.admin.enabled }}
    {{- with .Values.ingress.admin.host }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.ingress.admin.path }}
            pathType: {{ $.Values.ingress.admin.pathType }}
            backend:
              service:
                name: {{ include "inferplane.fullname" $ }}
                port:
                  name: admin
    {{- end }}
    {{- end }}
{{- end -}}
